2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Configure stats pid to 15480
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Administrator\.config\wandb\settings
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Loading settings from D:\STUDY ABROAD\project\minREV-main\minREV-main\wandb\settings
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'd:\\study abroad\\project\\minrev-main\\minrev-main\\main.py', 'program': 'd:\\study abroad\\project\\minrev-main\\minrev-main\\main.py'}
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-30 11:46:09,389 ERROR   MainThread:15480 [wandb_setup.py:_flush():78] error in wandb.init()
Traceback (most recent call last):
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 473, in exec_code
    exec_fun(compile(ast_code, filename, 'exec'), ns_globals, ns_locals)
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
  File "d:\study abroad\project\minrev-main\minrev-main\main.py", line 227, in <module>
    wandb.init(project="minrev")
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\wandb\sdk\wandb_init.py", line 1178, in init
    wandb._sentry.reraise(e)
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\wandb\analytics\sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\wandb\sdk\wandb_init.py", line 1163, in init
    wi.setup(kwargs)
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\wandb\sdk\wandb_init.py", line 300, in setup
    wandb_login._login(
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\wandb\sdk\wandb_login.py", line 334, in _login
    wlogin.prompt_api_key()
  File "D:\Programs\anaconda3\envs\pytorch_env\lib\site-packages\wandb\sdk\wandb_login.py", line 263, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:_log_setup():520] Logging user logs to D:\STUDY ABROAD\project\minREV-main\minREV-main\wandb\run-20240530_114609-c0297t81\logs\debug.log
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:_log_setup():521] Logging internal logs to D:\STUDY ABROAD\project\minREV-main\minREV-main\wandb\run-20240530_114609-c0297t81\logs\debug-internal.log
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():560] calling init triggers
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():610] starting backend
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():614] setting up manager
2024-05-30 11:46:09,389 INFO    MainThread:15480 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():622] backend started and connected
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():711] updated telemetry
2024-05-30 11:46:09,389 INFO    MainThread:15480 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-30 11:46:09,873 INFO    MainThread:15480 [wandb_run.py:_on_init():2396] communicating current version
2024-05-30 11:46:10,045 INFO    MainThread:15480 [wandb_run.py:_on_init():2405] got version response 
2024-05-30 11:46:10,045 INFO    MainThread:15480 [wandb_init.py:init():795] starting run threads in backend
2024-05-30 11:46:10,263 INFO    MainThread:15480 [wandb_run.py:_console_start():2374] atexit reg
2024-05-30 11:46:10,263 INFO    MainThread:15480 [wandb_run.py:_redirect():2229] redirect: wrap_raw
2024-05-30 11:46:10,263 INFO    MainThread:15480 [wandb_run.py:_redirect():2294] Wrapping output streams.
2024-05-30 11:46:10,263 INFO    MainThread:15480 [wandb_run.py:_redirect():2319] Redirects installed.
2024-05-30 11:46:10,263 INFO    MainThread:15480 [wandb_init.py:init():838] run started, returning control to user process
